/*
 * Organization Service
 *
 * This API is intended to manage organizations in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::organization::models;

#[derive(Debug, Serialize, Deserialize)]
pub struct V2Password {
	#[serde(rename = "password")]
	password: String,
	#[serde(rename = "changeRequired")]
	change_required: Option<bool>,
}

impl V2Password {
	pub fn new(password: String) -> V2Password {
		V2Password { password: password, change_required: None }
	}

	pub fn set_password(&mut self, password: String) {
		self.password = password;
	}

	pub fn with_password(mut self, password: String) -> V2Password {
		self.password = password;
		self
	}

	pub fn password(&self) -> &String {
		&self.password
	}

	pub fn set_change_required(&mut self, change_required: bool) {
		self.change_required = Some(change_required);
	}

	pub fn with_change_required(mut self, change_required: bool) -> V2Password {
		self.change_required = Some(change_required);
		self
	}

	pub fn change_required(&self) -> Option<&bool> {
		self.change_required.as_ref()
	}

	pub fn reset_change_required(&mut self) {
		self.change_required = None;
	}
}
