# SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
#
# SPDX-License-Identifier: Apache-2.0

coverage:
  status:
    project:
      default:
        # Do not pass if PR reduces coverage by more than 5%
        target: auto
        threshold: 5
comment:
  layout: "header, diff, components, files, footer"
