/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ManagementServiceListMachineKeysBody {
	#[serde(rename = "query")]
	query: Option<models::V1ListQuery>,
}

impl ManagementServiceListMachineKeysBody {
	pub fn new() -> ManagementServiceListMachineKeysBody {
		ManagementServiceListMachineKeysBody { query: None }
	}

	pub fn set_query(&mut self, query: models::V1ListQuery) {
		self.query = Some(query);
	}

	pub fn with_query(
		mut self,
		query: models::V1ListQuery,
	) -> ManagementServiceListMachineKeysBody {
		self.query = Some(query);
		self
	}

	pub fn query(&self) -> Option<&models::V1ListQuery> {
		self.query.as_ref()
	}

	pub fn reset_query(&mut self) {
		self.query = None;
	}
}
