/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ManagementServiceSetCustomVerifySmsotpMessageTextBody {
	#[serde(rename = "text")]
	text: Option<String>,
}

impl ManagementServiceSetCustomVerifySmsotpMessageTextBody {
	pub fn new() -> ManagementServiceSetCustomVerifySmsotpMessageTextBody {
		ManagementServiceSetCustomVerifySmsotpMessageTextBody { text: None }
	}

	pub fn set_text(&mut self, text: String) {
		self.text = Some(text);
	}

	pub fn with_text(
		mut self,
		text: String,
	) -> ManagementServiceSetCustomVerifySmsotpMessageTextBody {
		self.text = Some(text);
		self
	}

	pub fn text(&self) -> Option<&String> {
		self.text.as_ref()
	}

	pub fn reset_text(&mut self) {
		self.text = None;
	}
}
