/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Metadatav1Metadata {
	#[serde(rename = "details")]
	details: Option<models::V1ObjectDetails>,
	/// metadata key
	#[serde(rename = "key")]
	key: Option<String>,
	/// metadata value is base64 encoded, make sure to decode to get the value
	#[serde(rename = "value")]
	value: Option<String>,
}

impl Metadatav1Metadata {
	pub fn new() -> Metadatav1Metadata {
		Metadatav1Metadata { details: None, key: None, value: None }
	}

	pub fn set_details(&mut self, details: models::V1ObjectDetails) {
		self.details = Some(details);
	}

	pub fn with_details(mut self, details: models::V1ObjectDetails) -> Metadatav1Metadata {
		self.details = Some(details);
		self
	}

	pub fn details(&self) -> Option<&models::V1ObjectDetails> {
		self.details.as_ref()
	}

	pub fn reset_details(&mut self) {
		self.details = None;
	}

	pub fn set_key(&mut self, key: String) {
		self.key = Some(key);
	}

	pub fn with_key(mut self, key: String) -> Metadatav1Metadata {
		self.key = Some(key);
		self
	}

	pub fn key(&self) -> Option<&String> {
		self.key.as_ref()
	}

	pub fn reset_key(&mut self) {
		self.key = None;
	}

	pub fn set_value(&mut self, value: String) {
		self.value = Some(value);
	}

	pub fn with_value(mut self, value: String) -> Metadatav1Metadata {
		self.value = Some(value);
		self
	}

	pub fn value(&self) -> Option<&String> {
		self.value.as_ref()
	}

	pub fn reset_value(&mut self) {
		self.value = None;
	}
}
