/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1AddUserGrantResponse {
	#[serde(rename = "userGrantId")]
	user_grant_id: Option<String>,
	#[serde(rename = "details")]
	details: Option<models::V1ObjectDetails>,
}

impl V1AddUserGrantResponse {
	pub fn new() -> V1AddUserGrantResponse {
		V1AddUserGrantResponse { user_grant_id: None, details: None }
	}

	pub fn set_user_grant_id(&mut self, user_grant_id: String) {
		self.user_grant_id = Some(user_grant_id);
	}

	pub fn with_user_grant_id(mut self, user_grant_id: String) -> V1AddUserGrantResponse {
		self.user_grant_id = Some(user_grant_id);
		self
	}

	pub fn user_grant_id(&self) -> Option<&String> {
		self.user_grant_id.as_ref()
	}

	pub fn reset_user_grant_id(&mut self) {
		self.user_grant_id = None;
	}

	pub fn set_details(&mut self, details: models::V1ObjectDetails) {
		self.details = Some(details);
	}

	pub fn with_details(mut self, details: models::V1ObjectDetails) -> V1AddUserGrantResponse {
		self.details = Some(details);
		self
	}

	pub fn details(&self) -> Option<&models::V1ObjectDetails> {
		self.details.as_ref()
	}

	pub fn reset_details(&mut self) {
		self.details = None;
	}
}
