// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum V1ApiAuthMethodType {
	#[serde(rename = "API_AUTH_METHOD_TYPE_BASIC")]
	Basic,
	#[serde(rename = "API_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT")]
	PrivateKeyJwt,
}

impl V1ApiAuthMethodType {
	pub fn new() -> V1ApiAuthMethodType {
		V1ApiAuthMethodType::Basic
	}
}
