// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1AppQuery {
	#[serde(rename = "nameQuery")]
	name_query: Option<models::V1AppNameQuery>,
}

impl V1AppQuery {
	pub fn new() -> V1AppQuery {
		V1AppQuery { name_query: None }
	}

	pub fn set_name_query(&mut self, name_query: models::V1AppNameQuery) {
		self.name_query = Some(name_query);
	}

	pub fn with_name_query(mut self, name_query: models::V1AppNameQuery) -> V1AppQuery {
		self.name_query = Some(name_query);
		self
	}

	pub fn name_query(&self) -> Option<&models::V1AppNameQuery> {
		self.name_query.as_ref()
	}

	pub fn reset_name_query(&mut self) {
		self.name_query = None;
	}
}
