/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1BulkSetOrgMetadataRequestMetadata {
	#[serde(rename = "key")]
	key: Option<String>,
	#[serde(rename = "value")]
	value: Option<String>,
}

impl V1BulkSetOrgMetadataRequestMetadata {
	pub fn new() -> V1BulkSetOrgMetadataRequestMetadata {
		V1BulkSetOrgMetadataRequestMetadata { key: None, value: None }
	}

	pub fn set_key(&mut self, key: String) {
		self.key = Some(key);
	}

	pub fn with_key(mut self, key: String) -> V1BulkSetOrgMetadataRequestMetadata {
		self.key = Some(key);
		self
	}

	pub fn key(&self) -> Option<&String> {
		self.key.as_ref()
	}

	pub fn reset_key(&mut self) {
		self.key = None;
	}

	pub fn set_value(&mut self, value: String) {
		self.value = Some(value);
	}

	pub fn with_value(mut self, value: String) -> V1BulkSetOrgMetadataRequestMetadata {
		self.value = Some(value);
		self
	}

	pub fn value(&self) -> Option<&String> {
		self.value.as_ref()
	}

	pub fn reset_value(&mut self) {
		self.value = None;
	}
}
