/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1DomainPolicy {
	#[serde(rename = "details")]
	details: Option<models::V1ObjectDetails>,
	/// the username has to end with the domain of its organization
	#[serde(rename = "userLoginMustBeDomain")]
	user_login_must_be_domain: Option<bool>,
	/// defines if the organization's admin changed the policy
	#[serde(rename = "isDefault")]
	is_default: Option<bool>,
	/// defines if organization domains should be validated org count as
	/// validated automatically
	#[serde(rename = "validateOrgDomains")]
	validate_org_domains: Option<bool>,
	/// defines if the SMTP sender address domain should match an existing
	/// domain on the instance
	#[serde(rename = "smtpSenderAddressMatchesInstanceDomain")]
	smtp_sender_address_matches_instance_domain: Option<bool>,
}

impl V1DomainPolicy {
	pub fn new() -> V1DomainPolicy {
		V1DomainPolicy {
			details: None,
			user_login_must_be_domain: None,
			is_default: None,
			validate_org_domains: None,
			smtp_sender_address_matches_instance_domain: None,
		}
	}

	pub fn set_details(&mut self, details: models::V1ObjectDetails) {
		self.details = Some(details);
	}

	pub fn with_details(mut self, details: models::V1ObjectDetails) -> V1DomainPolicy {
		self.details = Some(details);
		self
	}

	pub fn details(&self) -> Option<&models::V1ObjectDetails> {
		self.details.as_ref()
	}

	pub fn reset_details(&mut self) {
		self.details = None;
	}

	pub fn set_user_login_must_be_domain(&mut self, user_login_must_be_domain: bool) {
		self.user_login_must_be_domain = Some(user_login_must_be_domain);
	}

	pub fn with_user_login_must_be_domain(
		mut self,
		user_login_must_be_domain: bool,
	) -> V1DomainPolicy {
		self.user_login_must_be_domain = Some(user_login_must_be_domain);
		self
	}

	pub fn user_login_must_be_domain(&self) -> Option<&bool> {
		self.user_login_must_be_domain.as_ref()
	}

	pub fn reset_user_login_must_be_domain(&mut self) {
		self.user_login_must_be_domain = None;
	}

	pub fn set_is_default(&mut self, is_default: bool) {
		self.is_default = Some(is_default);
	}

	pub fn with_is_default(mut self, is_default: bool) -> V1DomainPolicy {
		self.is_default = Some(is_default);
		self
	}

	pub fn is_default(&self) -> Option<&bool> {
		self.is_default.as_ref()
	}

	pub fn reset_is_default(&mut self) {
		self.is_default = None;
	}

	pub fn set_validate_org_domains(&mut self, validate_org_domains: bool) {
		self.validate_org_domains = Some(validate_org_domains);
	}

	pub fn with_validate_org_domains(mut self, validate_org_domains: bool) -> V1DomainPolicy {
		self.validate_org_domains = Some(validate_org_domains);
		self
	}

	pub fn validate_org_domains(&self) -> Option<&bool> {
		self.validate_org_domains.as_ref()
	}

	pub fn reset_validate_org_domains(&mut self) {
		self.validate_org_domains = None;
	}

	pub fn set_smtp_sender_address_matches_instance_domain(
		&mut self,
		smtp_sender_address_matches_instance_domain: bool,
	) {
		self.smtp_sender_address_matches_instance_domain =
			Some(smtp_sender_address_matches_instance_domain);
	}

	pub fn with_smtp_sender_address_matches_instance_domain(
		mut self,
		smtp_sender_address_matches_instance_domain: bool,
	) -> V1DomainPolicy {
		self.smtp_sender_address_matches_instance_domain =
			Some(smtp_sender_address_matches_instance_domain);
		self
	}

	pub fn smtp_sender_address_matches_instance_domain(&self) -> Option<&bool> {
		self.smtp_sender_address_matches_instance_domain.as_ref()
	}

	pub fn reset_smtp_sender_address_matches_instance_domain(&mut self) {
		self.smtp_sender_address_matches_instance_domain = None;
	}
}
