// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1EmailVerificationScreenText {
	#[serde(rename = "title")]
	title: Option<String>,
	#[serde(rename = "description")]
	description: Option<String>,
	#[serde(rename = "codeLabel")]
	code_label: Option<String>,
	#[serde(rename = "nextButtonText")]
	next_button_text: Option<String>,
	#[serde(rename = "resendButtonText")]
	resend_button_text: Option<String>,
}

impl V1EmailVerificationScreenText {
	pub fn new() -> V1EmailVerificationScreenText {
		V1EmailVerificationScreenText {
			title: None,
			description: None,
			code_label: None,
			next_button_text: None,
			resend_button_text: None,
		}
	}

	pub fn set_title(&mut self, title: String) {
		self.title = Some(title);
	}

	pub fn with_title(mut self, title: String) -> V1EmailVerificationScreenText {
		self.title = Some(title);
		self
	}

	pub fn title(&self) -> Option<&String> {
		self.title.as_ref()
	}

	pub fn reset_title(&mut self) {
		self.title = None;
	}

	pub fn set_description(&mut self, description: String) {
		self.description = Some(description);
	}

	pub fn with_description(mut self, description: String) -> V1EmailVerificationScreenText {
		self.description = Some(description);
		self
	}

	pub fn description(&self) -> Option<&String> {
		self.description.as_ref()
	}

	pub fn reset_description(&mut self) {
		self.description = None;
	}

	pub fn set_code_label(&mut self, code_label: String) {
		self.code_label = Some(code_label);
	}

	pub fn with_code_label(mut self, code_label: String) -> V1EmailVerificationScreenText {
		self.code_label = Some(code_label);
		self
	}

	pub fn code_label(&self) -> Option<&String> {
		self.code_label.as_ref()
	}

	pub fn reset_code_label(&mut self) {
		self.code_label = None;
	}

	pub fn set_next_button_text(&mut self, next_button_text: String) {
		self.next_button_text = Some(next_button_text);
	}

	pub fn with_next_button_text(
		mut self,
		next_button_text: String,
	) -> V1EmailVerificationScreenText {
		self.next_button_text = Some(next_button_text);
		self
	}

	pub fn next_button_text(&self) -> Option<&String> {
		self.next_button_text.as_ref()
	}

	pub fn reset_next_button_text(&mut self) {
		self.next_button_text = None;
	}

	pub fn set_resend_button_text(&mut self, resend_button_text: String) {
		self.resend_button_text = Some(resend_button_text);
	}

	pub fn with_resend_button_text(
		mut self,
		resend_button_text: String,
	) -> V1EmailVerificationScreenText {
		self.resend_button_text = Some(resend_button_text);
		self
	}

	pub fn resend_button_text(&self) -> Option<&String> {
		self.resend_button_text.as_ref()
	}

	pub fn reset_resend_button_text(&mut self) {
		self.resend_button_text = None;
	}
}
