/* 
 * Management API
 *
 * The management API is as the name states the interface where systems can mutate IAM objects like organizations, projects, clients, users and so on if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;
use crate::v2::management::models;
use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct V1GetOrgByDomainGlobalResponse {
  #[serde(rename = "org")]
  org: Option<models::Orgv1Org>
}

impl V1GetOrgByDomainGlobalResponse {
  pub fn new() -> V1GetOrgByDomainGlobalResponse {
    V1GetOrgByDomainGlobalResponse {
      org: None
    }
  }

  pub fn set_org(&mut self, org: models::Orgv1Org) {
    self.org = Some(org);
  }

  pub fn with_org(mut self, org: models::Orgv1Org) -> V1GetOrgByDomainGlobalResponse {
    self.org = Some(org);
    self
  }

  pub fn org(&self) -> Option<&models::Orgv1Org> {
    self.org.as_ref()
  }

  pub fn reset_org(&mut self) {
    self.org = None;
  }

}



