/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1GrantedOrgIdQuery {
	#[serde(rename = "grantedOrgId")]
	granted_org_id: Option<String>,
}

impl V1GrantedOrgIdQuery {
	pub fn new() -> V1GrantedOrgIdQuery {
		V1GrantedOrgIdQuery { granted_org_id: None }
	}

	pub fn set_granted_org_id(&mut self, granted_org_id: String) {
		self.granted_org_id = Some(granted_org_id);
	}

	pub fn with_granted_org_id(mut self, granted_org_id: String) -> V1GrantedOrgIdQuery {
		self.granted_org_id = Some(granted_org_id);
		self
	}

	pub fn granted_org_id(&self) -> Option<&String> {
		self.granted_org_id.as_ref()
	}

	pub fn reset_granted_org_id(&mut self) {
		self.granted_org_id = None;
	}
}
