// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1ListOrgMemberRolesResponse {
	#[serde(rename = "result")]
	result: Option<Vec<String>>,
}

impl V1ListOrgMemberRolesResponse {
	pub fn new() -> V1ListOrgMemberRolesResponse {
		V1ListOrgMemberRolesResponse { result: None }
	}

	pub fn set_result(&mut self, result: Vec<String>) {
		self.result = Some(result);
	}

	pub fn with_result(mut self, result: Vec<String>) -> V1ListOrgMemberRolesResponse {
		self.result = Some(result);
		self
	}

	pub fn result(&self) -> Option<&Vec<String>> {
		self.result.as_ref()
	}

	pub fn reset_result(&mut self) {
		self.result = None;
	}
}
