/* 
 * Management API
 *
 * The management API is as the name states the interface where systems can mutate IAM objects like organizations, projects, clients, users and so on if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;
use crate::v2::management::models;
use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct V1LocalizedMessage {
  #[serde(rename = "key")]
  key: Option<String>,
  #[serde(rename = "localizedMessage")]
  localized_message: Option<String>
}

impl V1LocalizedMessage {
  pub fn new() -> V1LocalizedMessage {
    V1LocalizedMessage {
      key: None,
      localized_message: None
    }
  }

  pub fn set_key(&mut self, key: String) {
    self.key = Some(key);
  }

  pub fn with_key(mut self, key: String) -> V1LocalizedMessage {
    self.key = Some(key);
    self
  }

  pub fn key(&self) -> Option<&String> {
    self.key.as_ref()
  }

  pub fn reset_key(&mut self) {
    self.key = None;
  }

  pub fn set_localized_message(&mut self, localized_message: String) {
    self.localized_message = Some(localized_message);
  }

  pub fn with_localized_message(mut self, localized_message: String) -> V1LocalizedMessage {
    self.localized_message = Some(localized_message);
    self
  }

  pub fn localized_message(&self) -> Option<&String> {
    self.localized_message.as_ref()
  }

  pub fn reset_localized_message(&mut self) {
    self.localized_message = None;
  }

}



