// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1ListProjectGrantMembersResponse {
	#[serde(rename = "details")]
	details: Option<models::V1ListDetails>,
	#[serde(rename = "result")]
	result: Option<Vec<models::V1Member>>,
}

impl V1ListProjectGrantMembersResponse {
	pub fn new() -> V1ListProjectGrantMembersResponse {
		V1ListProjectGrantMembersResponse { details: None, result: None }
	}

	pub fn set_details(&mut self, details: models::V1ListDetails) {
		self.details = Some(details);
	}

	pub fn with_details(
		mut self,
		details: models::V1ListDetails,
	) -> V1ListProjectGrantMembersResponse {
		self.details = Some(details);
		self
	}

	pub fn details(&self) -> Option<&models::V1ListDetails> {
		self.details.as_ref()
	}

	pub fn reset_details(&mut self) {
		self.details = None;
	}

	pub fn set_result(&mut self, result: Vec<models::V1Member>) {
		self.result = Some(result);
	}

	pub fn with_result(
		mut self,
		result: Vec<models::V1Member>,
	) -> V1ListProjectGrantMembersResponse {
		self.result = Some(result);
		self
	}

	pub fn result(&self) -> Option<&Vec<models::V1Member>> {
		self.result.as_ref()
	}

	pub fn reset_result(&mut self) {
		self.result = None;
	}
}
