/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1ListHumanPasswordlessResponse {
	#[serde(rename = "result")]
	result: Option<Vec<models::V1WebAuthNToken>>,
}

impl V1ListHumanPasswordlessResponse {
	pub fn new() -> V1ListHumanPasswordlessResponse {
		V1ListHumanPasswordlessResponse { result: None }
	}

	pub fn set_result(&mut self, result: Vec<models::V1WebAuthNToken>) {
		self.result = Some(result);
	}

	pub fn with_result(
		mut self,
		result: Vec<models::V1WebAuthNToken>,
	) -> V1ListHumanPasswordlessResponse {
		self.result = Some(result);
		self
	}

	pub fn result(&self) -> Option<&Vec<models::V1WebAuthNToken>> {
		self.result.as_ref()
	}

	pub fn reset_result(&mut self) {
		self.result = None;
	}
}
