// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1ListUsersRequest {
	#[serde(rename = "query")]
	query: Option<models::V1ListQuery>,
	#[serde(rename = "sortingColumn")]
	sorting_column: Option<models::V1UserFieldName>,
	#[serde(rename = "queries")]
	queries: Option<Vec<models::Zitadeluserv1SearchQuery>>,
}

impl V1ListUsersRequest {
	pub fn new() -> V1ListUsersRequest {
		V1ListUsersRequest { query: None, sorting_column: None, queries: None }
	}

	pub fn set_query(&mut self, query: models::V1ListQuery) {
		self.query = Some(query);
	}

	pub fn with_query(mut self, query: models::V1ListQuery) -> V1ListUsersRequest {
		self.query = Some(query);
		self
	}

	pub fn query(&self) -> Option<&models::V1ListQuery> {
		self.query.as_ref()
	}

	pub fn reset_query(&mut self) {
		self.query = None;
	}

	pub fn set_sorting_column(&mut self, sorting_column: models::V1UserFieldName) {
		self.sorting_column = Some(sorting_column);
	}

	pub fn with_sorting_column(
		mut self,
		sorting_column: models::V1UserFieldName,
	) -> V1ListUsersRequest {
		self.sorting_column = Some(sorting_column);
		self
	}

	pub fn sorting_column(&self) -> Option<&models::V1UserFieldName> {
		self.sorting_column.as_ref()
	}

	pub fn reset_sorting_column(&mut self) {
		self.sorting_column = None;
	}

	pub fn set_queries(&mut self, queries: Vec<models::Zitadeluserv1SearchQuery>) {
		self.queries = Some(queries);
	}

	pub fn with_queries(
		mut self,
		queries: Vec<models::Zitadeluserv1SearchQuery>,
	) -> V1ListUsersRequest {
		self.queries = Some(queries);
		self
	}

	pub fn queries(&self) -> Option<&Vec<models::Zitadeluserv1SearchQuery>> {
		self.queries.as_ref()
	}

	pub fn reset_queries(&mut self) {
		self.queries = None;
	}
}
