// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1LoginV2 {
	/// Optionally specify a base uri of the login UI. If unspecified the
	/// default URI will be used.
	#[serde(rename = "baseUri")]
	base_uri: Option<String>,
}

impl V1LoginV2 {
	pub fn new() -> V1LoginV2 {
		V1LoginV2 { base_uri: None }
	}

	pub fn set_base_uri(&mut self, base_uri: String) {
		self.base_uri = Some(base_uri);
	}

	pub fn with_base_uri(mut self, base_uri: String) -> V1LoginV2 {
		self.base_uri = Some(base_uri);
		self
	}

	pub fn base_uri(&self) -> Option<&String> {
		self.base_uri.as_ref()
	}

	pub fn reset_base_uri(&mut self) {
		self.base_uri = None;
	}
}
