// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1PasswordAgePolicy {
	#[serde(rename = "details")]
	details: Option<models::V1ObjectDetails>,
	/// Amount of days after which a password will expire. The user will be
	/// forced to change the password on the following authentication.
	#[serde(rename = "maxAgeDays")]
	max_age_days: Option<String>,
	/// Amount of days after which the user should be notified of the upcoming
	/// expiry. ZITADEL will not notify the user.
	#[serde(rename = "expireWarnDays")]
	expire_warn_days: Option<String>,
	/// If true, the returned values represent the instance settings, e.g. by an
	/// organization without custom settings.
	#[serde(rename = "isDefault")]
	is_default: Option<bool>,
}

impl V1PasswordAgePolicy {
	pub fn new() -> V1PasswordAgePolicy {
		V1PasswordAgePolicy {
			details: None,
			max_age_days: None,
			expire_warn_days: None,
			is_default: None,
		}
	}

	pub fn set_details(&mut self, details: models::V1ObjectDetails) {
		self.details = Some(details);
	}

	pub fn with_details(mut self, details: models::V1ObjectDetails) -> V1PasswordAgePolicy {
		self.details = Some(details);
		self
	}

	pub fn details(&self) -> Option<&models::V1ObjectDetails> {
		self.details.as_ref()
	}

	pub fn reset_details(&mut self) {
		self.details = None;
	}

	pub fn set_max_age_days(&mut self, max_age_days: String) {
		self.max_age_days = Some(max_age_days);
	}

	pub fn with_max_age_days(mut self, max_age_days: String) -> V1PasswordAgePolicy {
		self.max_age_days = Some(max_age_days);
		self
	}

	pub fn max_age_days(&self) -> Option<&String> {
		self.max_age_days.as_ref()
	}

	pub fn reset_max_age_days(&mut self) {
		self.max_age_days = None;
	}

	pub fn set_expire_warn_days(&mut self, expire_warn_days: String) {
		self.expire_warn_days = Some(expire_warn_days);
	}

	pub fn with_expire_warn_days(mut self, expire_warn_days: String) -> V1PasswordAgePolicy {
		self.expire_warn_days = Some(expire_warn_days);
		self
	}

	pub fn expire_warn_days(&self) -> Option<&String> {
		self.expire_warn_days.as_ref()
	}

	pub fn reset_expire_warn_days(&mut self) {
		self.expire_warn_days = None;
	}

	pub fn set_is_default(&mut self, is_default: bool) {
		self.is_default = Some(is_default);
	}

	pub fn with_is_default(mut self, is_default: bool) -> V1PasswordAgePolicy {
		self.is_default = Some(is_default);
		self
	}

	pub fn is_default(&self) -> Option<&bool> {
		self.is_default.as_ref()
	}

	pub fn reset_is_default(&mut self) {
		self.is_default = None;
	}
}
