// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct V1UserGrantProjectIdQuery {
	#[serde(rename = "projectId")]
	project_id: Option<String>,
}

impl V1UserGrantProjectIdQuery {
	pub fn new() -> V1UserGrantProjectIdQuery {
		V1UserGrantProjectIdQuery { project_id: None }
	}

	pub fn set_project_id(&mut self, project_id: String) {
		self.project_id = Some(project_id);
	}

	pub fn with_project_id(mut self, project_id: String) -> V1UserGrantProjectIdQuery {
		self.project_id = Some(project_id);
		self
	}

	pub fn project_id(&self) -> Option<&String> {
		self.project_id.as_ref()
	}

	pub fn reset_project_id(&mut self) {
		self.project_id = None;
	}
}
