/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum V1UserState {
	USER_STATE_UNSPECIFIED,
	USER_STATE_ACTIVE,
	USER_STATE_INACTIVE,
	USER_STATE_DELETED,
	USER_STATE_LOCKED,
	USER_STATE_SUSPEND,
	USER_STATE_INITIAL,
}
