/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use famedly_rust_utils::GenericCombinators;
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum V1UserGrantQuery {
	ProjectId {
		#[serde(rename = "projectIdQuery")]
		project_id_query: models::V1UserGrantProjectIdQuery,
	},
	UserId {
		#[serde(rename = "userIdQuery")]
		user_id_query: models::V1UserGrantUserIdQuery,
	},
	WithGranted {
		#[serde(rename = "withGrantedQuery")]
		with_granted_query: models::V1UserGrantWithGrantedQuery,
	},
	RoleKey {
		#[serde(rename = "roleKeyQuery")]
		role_key_query: models::V1UserGrantRoleKeyQuery,
	},
	ProjectGrantId {
		#[serde(rename = "projectGrantIdQuery")]
		project_grant_id_query: models::V1UserGrantProjectGrantIdQuery,
	},
	UserName {
		#[serde(rename = "userNameQuery")]
		user_name_query: models::V1UserGrantUserNameQuery,
	},
	FirstName {
		#[serde(rename = "firstNameQuery")]
		first_name_query: models::V1UserGrantFirstNameQuery,
	},
	LastName {
		#[serde(rename = "lastNameQuery")]
		last_name_query: models::V1UserGrantLastNameQuery,
	},
	Email {
		#[serde(rename = "emailQuery")]
		email_query: models::V1UserGrantEmailQuery,
	},
	OrgName {
		#[serde(rename = "orgNameQuery")]
		org_name_query: models::V1UserGrantOrgNameQuery,
	},
	OrgDomain {
		#[serde(rename = "orgDomainQuery")]
		org_domain_query: models::V1UserGrantOrgDomainQuery,
	},
	ProjectName {
		#[serde(rename = "projectNameQuery")]
		project_name_query: models::V1UserGrantProjectNameQuery,
	},
	DisplayName {
		#[serde(rename = "displayNameQuery")]
		display_name_query: models::V1UserGrantDisplayNameQuery,
	},
	UserType {
		#[serde(rename = "userTypeQuery")]
		user_type_query: models::V1UserGrantUserTypeQuery,
	},
}

impl crate::v2::pagination::PaginationRequest for Option<Vec<V1UserGrantQuery>> {
	type Item = models::V1ListUserGrantRequest;
	#[allow(clippy::cast_possible_wrap)]
	fn to_paginated_request(&self, page: usize) -> Self::Item {
		let page = models::V1ListQuery::new()
			.with_limit(self.page_size() as i64)
			.with_offset((page * self.page_size()).to_string());
		// .with_asc(self.asc.unwrap_or_default());
		Self::Item::new().with_query(page).chain_opt(self.clone(), Self::Item::with_queries)
	}

	fn page_size(&self) -> usize {
		1000
	}
}
