/* 
 * Management API
 *
 * The management API is as the name states the interface where systems can mutate IAM objects like organizations, projects, clients, users and so on if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;
use crate::v2::management::models;
use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct V1UserGrantProjectGrantIdQuery {
  #[serde(rename = "projectGrantId")]
  project_grant_id: Option<String>
}

impl V1UserGrantProjectGrantIdQuery {
  pub fn new() -> V1UserGrantProjectGrantIdQuery {
    V1UserGrantProjectGrantIdQuery {
      project_grant_id: None
    }
  }

  pub fn set_project_grant_id(&mut self, project_grant_id: String) {
    self.project_grant_id = Some(project_grant_id);
  }

  pub fn with_project_grant_id(mut self, project_grant_id: String) -> V1UserGrantProjectGrantIdQuery {
    self.project_grant_id = Some(project_grant_id);
    self
  }

  pub fn project_grant_id(&self) -> Option<&String> {
    self.project_grant_id.as_ref()
  }

  pub fn reset_project_grant_id(&mut self) {
    self.project_grant_id = None;
  }

}



