// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Zitadelmanagementv1GetPrivacyPolicyResponse {
	#[serde(rename = "policy")]
	policy: Option<models::V1PrivacyPolicy>,
}

impl Zitadelmanagementv1GetPrivacyPolicyResponse {
	pub fn new() -> Zitadelmanagementv1GetPrivacyPolicyResponse {
		Zitadelmanagementv1GetPrivacyPolicyResponse { policy: None }
	}

	pub fn set_policy(&mut self, policy: models::V1PrivacyPolicy) {
		self.policy = Some(policy);
	}

	pub fn with_policy(
		mut self,
		policy: models::V1PrivacyPolicy,
	) -> Zitadelmanagementv1GetPrivacyPolicyResponse {
		self.policy = Some(policy);
		self
	}

	pub fn policy(&self) -> Option<&models::V1PrivacyPolicy> {
		self.policy.as_ref()
	}

	pub fn reset_policy(&mut self) {
		self.policy = None;
	}
}
