/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Zitadelmanagementv1GetCustomLoginTextsResponse {
	#[serde(rename = "customText")]
	custom_text: Option<models::V1LoginCustomText>,
}

impl Zitadelmanagementv1GetCustomLoginTextsResponse {
	pub fn new() -> Zitadelmanagementv1GetCustomLoginTextsResponse {
		Zitadelmanagementv1GetCustomLoginTextsResponse { custom_text: None }
	}

	pub fn set_custom_text(&mut self, custom_text: models::V1LoginCustomText) {
		self.custom_text = Some(custom_text);
	}

	pub fn with_custom_text(
		mut self,
		custom_text: models::V1LoginCustomText,
	) -> Zitadelmanagementv1GetCustomLoginTextsResponse {
		self.custom_text = Some(custom_text);
		self
	}

	pub fn custom_text(&self) -> Option<&models::V1LoginCustomText> {
		self.custom_text.as_ref()
	}

	pub fn reset_custom_text(&mut self) {
		self.custom_text = None;
	}
}
