// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Management API
 *
 * The management API is as the name states the interface where systems can
 * mutate IAM objects like organizations, projects, clients, users and so on
 * if they have the necessary access rights.
 *
 * OpenAPI spec version: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::v2::management::models;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Zitadelidpv1OidcConfig {
	/// client id generated by the identity provider
	#[serde(rename = "clientId")]
	client_id: Option<String>,
	/// the OIDC issuer of the identity provider
	#[serde(rename = "issuer")]
	issuer: Option<String>,
	/// the scopes requested by ZITADEL during the request on the identity
	/// provider
	#[serde(rename = "scopes")]
	scopes: Option<Vec<String>>,
	/// definition which field is mapped to the display name of the user
	#[serde(rename = "displayNameMapping")]
	display_name_mapping: Option<models::V1OidcMappingField>,
	/// definition which field is mapped to the email of the user
	#[serde(rename = "usernameMapping")]
	username_mapping: Option<models::V1OidcMappingField>,
}

impl Zitadelidpv1OidcConfig {
	pub fn new() -> Zitadelidpv1OidcConfig {
		Zitadelidpv1OidcConfig {
			client_id: None,
			issuer: None,
			scopes: None,
			display_name_mapping: None,
			username_mapping: None,
		}
	}

	pub fn set_client_id(&mut self, client_id: String) {
		self.client_id = Some(client_id);
	}

	pub fn with_client_id(mut self, client_id: String) -> Zitadelidpv1OidcConfig {
		self.client_id = Some(client_id);
		self
	}

	pub fn client_id(&self) -> Option<&String> {
		self.client_id.as_ref()
	}

	pub fn reset_client_id(&mut self) {
		self.client_id = None;
	}

	pub fn set_issuer(&mut self, issuer: String) {
		self.issuer = Some(issuer);
	}

	pub fn with_issuer(mut self, issuer: String) -> Zitadelidpv1OidcConfig {
		self.issuer = Some(issuer);
		self
	}

	pub fn issuer(&self) -> Option<&String> {
		self.issuer.as_ref()
	}

	pub fn reset_issuer(&mut self) {
		self.issuer = None;
	}

	pub fn set_scopes(&mut self, scopes: Vec<String>) {
		self.scopes = Some(scopes);
	}

	pub fn with_scopes(mut self, scopes: Vec<String>) -> Zitadelidpv1OidcConfig {
		self.scopes = Some(scopes);
		self
	}

	pub fn scopes(&self) -> Option<&Vec<String>> {
		self.scopes.as_ref()
	}

	pub fn reset_scopes(&mut self) {
		self.scopes = None;
	}

	pub fn set_display_name_mapping(&mut self, display_name_mapping: models::V1OidcMappingField) {
		self.display_name_mapping = Some(display_name_mapping);
	}

	pub fn with_display_name_mapping(
		mut self,
		display_name_mapping: models::V1OidcMappingField,
	) -> Zitadelidpv1OidcConfig {
		self.display_name_mapping = Some(display_name_mapping);
		self
	}

	pub fn display_name_mapping(&self) -> Option<&models::V1OidcMappingField> {
		self.display_name_mapping.as_ref()
	}

	pub fn reset_display_name_mapping(&mut self) {
		self.display_name_mapping = None;
	}

	pub fn set_username_mapping(&mut self, username_mapping: models::V1OidcMappingField) {
		self.username_mapping = Some(username_mapping);
	}

	pub fn with_username_mapping(
		mut self,
		username_mapping: models::V1OidcMappingField,
	) -> Zitadelidpv1OidcConfig {
		self.username_mapping = Some(username_mapping);
		self
	}

	pub fn username_mapping(&self) -> Option<&models::V1OidcMappingField> {
		self.username_mapping.as_ref()
	}

	pub fn reset_username_mapping(&mut self) {
		self.username_mapping = None;
	}
}
