experimental = ["setup-scripts"]

[test-groups]
# E2E tests rely on syncing data from other sources;
# if multiple tests create users simultaneously,
# one thread will "win" and sync its users first
# (or nobody wins and a bunch of tests try to create users that
# already exist) - we don't want this.
e2e = { max-threads = 1 }

[script.start-e2e-env]
command =  "./.config/starte2e.sh"

[[profile.default.scripts]]
filter = "test(e2e)"
setup = "start-e2e-env"

[[profile.default.overrides]]
filter = "test(e2e)"
test-group = "e2e"

[profile.ci]
fail-fast = false

[profile.ci.junit]
path = "junit.xml"
store-success-output = true
store-failure-output = true
