// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

use crate::v2::users::models;

#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct CreateInviteCodeResponse {
	#[serde(rename = "details")]
	details: Option<models::Details>,
	#[serde(rename = "inviteCode")]
	invite_code: Option<String>,
}

impl CreateInviteCodeResponse {
	pub fn new() -> CreateInviteCodeResponse {
		CreateInviteCodeResponse { details: None, invite_code: None }
	}

	pub fn set_details(&mut self, details: models::Details) {
		self.details = Some(details);
	}

	pub fn with_details(mut self, details: models::Details) -> CreateInviteCodeResponse {
		self.details = Some(details);
		self
	}

	pub fn details(&self) -> Option<&models::Details> {
		self.details.as_ref()
	}

	pub fn reset_details(&mut self) {
		self.details = None;
	}

	pub fn set_invite_code(&mut self, invite_code: String) {
		self.invite_code = Some(invite_code);
	}

	pub fn with_invite_code(mut self, invite_code: String) -> CreateInviteCodeResponse {
		self.invite_code = Some(invite_code);
		self
	}

	pub fn invite_code(&self) -> Option<&String> {
		self.invite_code.as_ref()
	}

	pub fn reset_invite_code(&mut self) {
		self.invite_code = None;
	}
}
