/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

use crate::v2::users::models;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct NickNameQuery {
	#[serde(rename = "nickName")]
	nick_name: String,
	/// defines which text equality method is used
	#[serde(rename = "method")]
	method: Option<models::TextQueryMethod>,
}

impl NickNameQuery {
	/// Query for users with a specific nickname.
	pub fn new(nick_name: String) -> NickNameQuery {
		NickNameQuery { nick_name, method: None }
	}

	pub fn set_nick_name(&mut self, nick_name: String) {
		self.nick_name = nick_name;
	}

	pub fn with_nick_name(mut self, nick_name: String) -> NickNameQuery {
		self.nick_name = nick_name;
		self
	}

	pub fn nick_name(&self) -> &String {
		&self.nick_name
	}

	pub fn set_method(&mut self, method: models::TextQueryMethod) {
		self.method = Some(method);
	}

	pub fn with_method(mut self, method: models::TextQueryMethod) -> NickNameQuery {
		self.method = Some(method);
		self
	}

	pub fn method(&self) -> Option<&models::TextQueryMethod> {
		self.method.as_ref()
	}

	pub fn reset_method(&mut self) {
		self.method = None;
	}
}
