// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

use crate::v2::users::models;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct UserServiceSetPhoneBody {
	#[serde(rename = "phone")]
	phone: String,
	#[serde(rename = "sendCode")]
	send_code: Option<models::SendPhoneVerificationCode>,
	#[serde(rename = "returnCode")]
	return_code: Option<models::ReturnPhoneVerificationCode>,
	#[serde(rename = "isVerified")]
	is_verified: Option<bool>,
}

impl UserServiceSetPhoneBody {
	pub fn new(phone: String) -> UserServiceSetPhoneBody {
		UserServiceSetPhoneBody { phone, send_code: None, return_code: None, is_verified: None }
	}

	pub fn set_phone(&mut self, phone: String) {
		self.phone = phone;
	}

	pub fn with_phone(mut self, phone: String) -> UserServiceSetPhoneBody {
		self.phone = phone;
		self
	}

	pub fn phone(&self) -> &String {
		&self.phone
	}

	pub fn set_send_code(&mut self, send_code: models::SendPhoneVerificationCode) {
		self.send_code = Some(send_code);
	}

	pub fn with_send_code(
		mut self,
		send_code: models::SendPhoneVerificationCode,
	) -> UserServiceSetPhoneBody {
		self.send_code = Some(send_code);
		self
	}

	pub fn send_code(&self) -> Option<&models::SendPhoneVerificationCode> {
		self.send_code.as_ref()
	}

	pub fn reset_send_code(&mut self) {
		self.send_code = None;
	}

	pub fn set_return_code(&mut self, return_code: models::ReturnPhoneVerificationCode) {
		self.return_code = Some(return_code);
	}

	pub fn with_return_code(
		mut self,
		return_code: models::ReturnPhoneVerificationCode,
	) -> UserServiceSetPhoneBody {
		self.return_code = Some(return_code);
		self
	}

	pub fn return_code(&self) -> Option<&models::ReturnPhoneVerificationCode> {
		self.return_code.as_ref()
	}

	pub fn reset_return_code(&mut self) {
		self.return_code = None;
	}

	pub fn set_is_verified(&mut self, is_verified: bool) {
		self.is_verified = Some(is_verified);
	}

	pub fn with_is_verified(mut self, is_verified: bool) -> UserServiceSetPhoneBody {
		self.is_verified = Some(is_verified);
		self
	}

	pub fn is_verified(&self) -> Option<&bool> {
		self.is_verified.as_ref()
	}

	pub fn reset_is_verified(&mut self) {
		self.is_verified = None;
	}
}
