/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

use crate::v2::users::models;

#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct UserServiceListIdpLinksBody {
	#[serde(rename = "query")]
	query: Option<models::ListQuery>,
}

impl UserServiceListIdpLinksBody {
	pub fn new() -> UserServiceListIdpLinksBody {
		UserServiceListIdpLinksBody { query: None }
	}

	pub fn with_query(mut self, query: models::ListQuery) -> UserServiceListIdpLinksBody {
		self.query = Some(query);
		self
	}
}
