// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

use crate::v2::users::models;

#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct UserServiceCreateInviteCodeBody {
	#[serde(rename = "sendCode")]
	send_code: Option<models::SendInviteCode>,
	#[serde(rename = "returnCode")]
	return_code: Option<models::ReturnInviteCode>,
}

impl UserServiceCreateInviteCodeBody {
	pub fn new() -> UserServiceCreateInviteCodeBody {
		UserServiceCreateInviteCodeBody { send_code: None, return_code: None }
	}

	pub fn set_send_code(&mut self, send_code: models::SendInviteCode) {
		self.send_code = Some(send_code);
	}

	pub fn with_send_code(
		mut self,
		send_code: models::SendInviteCode,
	) -> UserServiceCreateInviteCodeBody {
		self.send_code = Some(send_code);
		self
	}

	pub fn send_code(&self) -> Option<&models::SendInviteCode> {
		self.send_code.as_ref()
	}

	pub fn reset_send_code(&mut self) {
		self.send_code = None;
	}

	pub fn set_return_code(&mut self, return_code: models::ReturnInviteCode) {
		self.return_code = Some(return_code);
	}

	pub fn with_return_code(
		mut self,
		return_code: models::ReturnInviteCode,
	) -> UserServiceCreateInviteCodeBody {
		self.return_code = Some(return_code);
		self
	}

	pub fn return_code(&self) -> Option<&models::ReturnInviteCode> {
		self.return_code.as_ref()
	}

	pub fn reset_return_code(&mut self) {
		self.return_code = None;
	}
}
