// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

use crate::v2::users::models;

#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct UserServiceUpdateUserBody {
	/// Set a new username that is unique within the instance. Beware that
	/// active tokens and sessions are invalidated when the username is
	/// changed.
	#[serde(rename = "username")]
	username: Option<String>,
	#[serde(rename = "human")]
	human: Option<models::V2UpdateUserRequestHuman>,
	#[serde(rename = "machine")]
	machine: Option<models::V2UpdateUserRequestMachine>,
	/// Metadata to be set. Metadata is expected as key-value pairs, and the
	/// value has to be base64 encoded.
	#[serde(rename = "metadata")]
	metadata: Option<Vec<models::ZitadelUserV2Metadata>>,
}

impl UserServiceUpdateUserBody {
	pub fn new() -> UserServiceUpdateUserBody {
		UserServiceUpdateUserBody { username: None, human: None, machine: None, metadata: None }
	}

	pub fn set_username(&mut self, username: String) {
		self.username = Some(username);
	}

	pub fn with_username(mut self, username: String) -> UserServiceUpdateUserBody {
		self.username = Some(username);
		self
	}

	pub fn username(&self) -> Option<&String> {
		self.username.as_ref()
	}

	pub fn reset_username(&mut self) {
		self.username = None;
	}

	pub fn set_human(&mut self, human: models::V2UpdateUserRequestHuman) {
		self.human = Some(human);
	}

	pub fn with_human(
		mut self,
		human: models::V2UpdateUserRequestHuman,
	) -> UserServiceUpdateUserBody {
		self.human = Some(human);
		self
	}

	pub fn human(&self) -> Option<&models::V2UpdateUserRequestHuman> {
		self.human.as_ref()
	}

	pub fn reset_human(&mut self) {
		self.human = None;
	}

	pub fn set_machine(&mut self, machine: models::V2UpdateUserRequestMachine) {
		self.machine = Some(machine);
	}

	pub fn with_machine(
		mut self,
		machine: models::V2UpdateUserRequestMachine,
	) -> UserServiceUpdateUserBody {
		self.machine = Some(machine);
		self
	}

	pub fn machine(&self) -> Option<&models::V2UpdateUserRequestMachine> {
		self.machine.as_ref()
	}

	pub fn reset_machine(&mut self) {
		self.machine = None;
	}

	pub fn set_metadata(&mut self, metadata: Vec<models::ZitadelUserV2Metadata>) {
		self.metadata = Some(metadata);
	}

	pub fn with_metadata(
		mut self,
		metadata: Vec<models::ZitadelUserV2Metadata>,
	) -> UserServiceUpdateUserBody {
		self.metadata = Some(metadata);
		self
	}

	pub fn metadata(&self) -> Option<&Vec<models::ZitadelUserV2Metadata>> {
		self.metadata.as_ref()
	}

	pub fn reset_metadata(&mut self) {
		self.metadata = None;
	}
}
