// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct V2UpdateUserResponse {
	/// The timestamp of the change of the user.
	#[serde(rename = "changeDate")]
	change_date: Option<String>,
	#[serde(rename = "emailCode")]
	email_code: Option<String>,
	#[serde(rename = "phoneCode")]
	phone_code: Option<String>,
}

impl V2UpdateUserResponse {
	pub fn new() -> V2UpdateUserResponse {
		V2UpdateUserResponse { change_date: None, email_code: None, phone_code: None }
	}

	pub fn set_change_date(&mut self, change_date: String) {
		self.change_date = Some(change_date);
	}

	pub fn with_change_date(mut self, change_date: String) -> V2UpdateUserResponse {
		self.change_date = Some(change_date);
		self
	}

	pub fn change_date(&self) -> Option<&String> {
		self.change_date.as_ref()
	}

	pub fn reset_change_date(&mut self) {
		self.change_date = None;
	}

	pub fn set_email_code(&mut self, email_code: String) {
		self.email_code = Some(email_code);
	}

	pub fn with_email_code(mut self, email_code: String) -> V2UpdateUserResponse {
		self.email_code = Some(email_code);
		self
	}

	pub fn email_code(&self) -> Option<&String> {
		self.email_code.as_ref()
	}

	pub fn reset_email_code(&mut self) {
		self.email_code = None;
	}

	pub fn set_phone_code(&mut self, phone_code: String) {
		self.phone_code = Some(phone_code);
	}

	pub fn with_phone_code(mut self, phone_code: String) -> V2UpdateUserResponse {
		self.phone_code = Some(phone_code);
		self
	}

	pub fn phone_code(&self) -> Option<&String> {
		self.phone_code.as_ref()
	}

	pub fn reset_phone_code(&mut self) {
		self.phone_code = None;
	}
}
