// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a ZITADEL instance. This service is in beta state. It can AND
 * will continue breaking until a stable version is released.
 *
 * OpenAPI spec version: 2.0-beta
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2Condition {
	/// Condition-type to execute if a request on the defined API point happens.
	#[serde(rename = "request")]
	request: Option<super::V2RequestExecution>,
	/// Condition-type to execute on response if a request on the defined API
	/// point happens.
	#[serde(rename = "response")]
	response: Option<super::V2ResponseExecution>,
	/// Condition-type to execute if function is used, replaces actions v1.
	#[serde(rename = "function")]
	function: Option<super::V2FunctionExecution>,
	/// Condition-type to execute if an event is created in the system.
	#[serde(rename = "event")]
	event: Option<super::V2EventExecution>,
}

impl V2Condition {
	pub fn new() -> V2Condition {
		V2Condition { request: None, response: None, function: None, event: None }
	}

	pub fn set_request(&mut self, request: super::V2RequestExecution) {
		self.request = Some(request);
	}

	pub fn with_request(mut self, request: super::V2RequestExecution) -> V2Condition {
		self.request = Some(request);
		self
	}

	pub fn request(&self) -> Option<&super::V2RequestExecution> {
		self.request.as_ref()
	}

	pub fn reset_request(&mut self) {
		self.request = None;
	}

	pub fn set_response(&mut self, response: super::V2ResponseExecution) {
		self.response = Some(response);
	}

	pub fn with_response(mut self, response: super::V2ResponseExecution) -> V2Condition {
		self.response = Some(response);
		self
	}

	pub fn response(&self) -> Option<&super::V2ResponseExecution> {
		self.response.as_ref()
	}

	pub fn reset_response(&mut self) {
		self.response = None;
	}

	pub fn set_function(&mut self, function: super::V2FunctionExecution) {
		self.function = Some(function);
	}

	pub fn with_function(mut self, function: super::V2FunctionExecution) -> V2Condition {
		self.function = Some(function);
		self
	}

	pub fn function(&self) -> Option<&super::V2FunctionExecution> {
		self.function.as_ref()
	}

	pub fn reset_function(&mut self) {
		self.function = None;
	}

	pub fn set_event(&mut self, event: super::V2EventExecution) {
		self.event = Some(event);
	}

	pub fn with_event(mut self, event: super::V2EventExecution) -> V2Condition {
		self.event = Some(event);
		self
	}

	pub fn event(&self) -> Option<&super::V2EventExecution> {
		self.event.as_ref()
	}

	pub fn reset_event(&mut self) {
		self.event = None;
	}
}
