// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2Execution {
	/// The condition under which the execution is triggered.
	#[serde(rename = "condition")]
	#[serde(skip_serializing_if = "Option::is_none")]
	condition: Option<super::V2Condition>,
	/// The timestamp of the execution creation.
	#[serde(rename = "creationDate")]
	#[serde(skip_serializing_if = "Option::is_none")]
	creation_date: Option<String>,
	/// The timestamp of the last change to the execution.
	#[serde(rename = "changeDate")]
	#[serde(skip_serializing_if = "Option::is_none")]
	change_date: Option<String>,
	/// Ordered list of targets called during the execution. The order of the
	/// targets in this list defines the order of execution. If one of the
	/// targets fails, depending on the target's type and settings, the
	/// execution might be interrupted and the following targets will not be
	/// called.
	#[serde(rename = "targets")]
	#[serde(skip_serializing_if = "Option::is_none")]
	targets: Option<Vec<String>>,
}

impl V2Execution {
	pub fn new() -> V2Execution {
		V2Execution { condition: None, creation_date: None, change_date: None, targets: None }
	}

	pub fn set_condition(&mut self, condition: super::V2Condition) {
		self.condition = Some(condition);
	}

	pub fn with_condition(mut self, condition: super::V2Condition) -> V2Execution {
		self.condition = Some(condition);
		self
	}

	pub fn condition(&self) -> Option<&super::V2Condition> {
		self.condition.as_ref()
	}

	pub fn reset_condition(&mut self) {
		self.condition = None;
	}

	pub fn set_creation_date(&mut self, creation_date: String) {
		self.creation_date = Some(creation_date);
	}

	pub fn with_creation_date(mut self, creation_date: String) -> V2Execution {
		self.creation_date = Some(creation_date);
		self
	}

	pub fn creation_date(&self) -> Option<&String> {
		self.creation_date.as_ref()
	}

	pub fn reset_creation_date(&mut self) {
		self.creation_date = None;
	}

	pub fn set_change_date(&mut self, change_date: String) {
		self.change_date = Some(change_date);
	}

	pub fn with_change_date(mut self, change_date: String) -> V2Execution {
		self.change_date = Some(change_date);
		self
	}

	pub fn change_date(&self) -> Option<&String> {
		self.change_date.as_ref()
	}

	pub fn reset_change_date(&mut self) {
		self.change_date = None;
	}

	pub fn set_targets(&mut self, targets: Vec<String>) {
		self.targets = Some(targets);
	}

	pub fn with_targets(mut self, targets: Vec<String>) -> V2Execution {
		self.targets = Some(targets);
		self
	}

	pub fn targets(&self) -> Option<&Vec<String>> {
		self.targets.as_ref()
	}

	pub fn reset_targets(&mut self) {
		self.targets = None;
	}
}
