// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2EventExecution {
	/// Define a specific event as condition. After this event is created, the
	/// execution is triggered.
	#[serde(rename = "event")]
	#[serde(skip_serializing_if = "Option::is_none")]
	event: Option<String>,
	/// Define an event group as condition. After any event under this group is
	/// created, the execution is triggered.
	#[serde(rename = "group")]
	#[serde(skip_serializing_if = "Option::is_none")]
	group: Option<String>,
	/// Define all events as condition. After any event is created, the
	/// execution is triggered.
	#[serde(rename = "all")]
	#[serde(skip_serializing_if = "Option::is_none")]
	all: Option<bool>,
}

impl V2EventExecution {
	pub fn new() -> V2EventExecution {
		V2EventExecution { event: None, group: None, all: None }
	}

	pub fn set_event(&mut self, event: String) {
		self.event = Some(event);
	}

	pub fn with_event(mut self, event: String) -> V2EventExecution {
		self.event = Some(event);
		self
	}

	pub fn event(&self) -> Option<&String> {
		self.event.as_ref()
	}

	pub fn reset_event(&mut self) {
		self.event = None;
	}

	pub fn set_group(&mut self, group: String) {
		self.group = Some(group);
	}

	pub fn with_group(mut self, group: String) -> V2EventExecution {
		self.group = Some(group);
		self
	}

	pub fn group(&self) -> Option<&String> {
		self.group.as_ref()
	}

	pub fn reset_group(&mut self) {
		self.group = None;
	}

	pub fn set_all(&mut self, all: bool) {
		self.all = Some(all);
	}

	pub fn with_all(mut self, all: bool) -> V2EventExecution {
		self.all = Some(all);
		self
	}

	pub fn all(&self) -> Option<&bool> {
		self.all.as_ref()
	}

	pub fn reset_all(&mut self) {
		self.all = None;
	}
}
