// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2InTargetIdsFilter {
	/// Defines the ids to query for.
	#[serde(rename = "targetIds")]
	#[serde(skip_serializing_if = "Option::is_none")]
	target_ids: Option<Vec<String>>,
}

impl V2InTargetIdsFilter {
	pub fn new() -> V2InTargetIdsFilter {
		V2InTargetIdsFilter { target_ids: None }
	}

	pub fn set_target_ids(&mut self, target_ids: Vec<String>) {
		self.target_ids = Some(target_ids);
	}

	pub fn with_target_ids(mut self, target_ids: Vec<String>) -> V2InTargetIdsFilter {
		self.target_ids = Some(target_ids);
		self
	}

	pub fn target_ids(&self) -> Option<&Vec<String>> {
		self.target_ids.as_ref()
	}

	pub fn reset_target_ids(&mut self) {
		self.target_ids = None;
	}
}
