// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2ListExecutionServicesResponse {
	/// All available services to use in conditions.
	#[serde(rename = "services")]
	#[serde(skip_serializing_if = "Option::is_none")]
	services: Option<Vec<String>>,
}

impl V2ListExecutionServicesResponse {
	pub fn new() -> V2ListExecutionServicesResponse {
		V2ListExecutionServicesResponse { services: None }
	}

	pub fn set_services(&mut self, services: Vec<String>) {
		self.services = Some(services);
	}

	pub fn with_services(mut self, services: Vec<String>) -> V2ListExecutionServicesResponse {
		self.services = Some(services);
		self
	}

	pub fn services(&self) -> Option<&Vec<String>> {
		self.services.as_ref()
	}

	pub fn reset_services(&mut self) {
		self.services = None;
	}
}
