// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2ListPublicKeysResponse {
	/// List limitations and ordering.
	#[serde(rename = "pagination")]
	#[serde(skip_serializing_if = "Option::is_none")]
	pagination: Option<super::V2PaginationResponse>,
	/// List of all public keys for the target.
	#[serde(rename = "publicKeys")]
	#[serde(skip_serializing_if = "Option::is_none")]
	public_keys: Option<Vec<super::V2PublicKey>>,
}

impl V2ListPublicKeysResponse {
	pub fn new() -> V2ListPublicKeysResponse {
		V2ListPublicKeysResponse { pagination: None, public_keys: None }
	}

	pub fn set_pagination(&mut self, pagination: super::V2PaginationResponse) {
		self.pagination = Some(pagination);
	}

	pub fn with_pagination(
		mut self,
		pagination: super::V2PaginationResponse,
	) -> V2ListPublicKeysResponse {
		self.pagination = Some(pagination);
		self
	}

	pub fn pagination(&self) -> Option<&super::V2PaginationResponse> {
		self.pagination.as_ref()
	}

	pub fn reset_pagination(&mut self) {
		self.pagination = None;
	}

	pub fn set_public_keys(&mut self, public_keys: Vec<super::V2PublicKey>) {
		self.public_keys = Some(public_keys);
	}

	pub fn with_public_keys(
		mut self,
		public_keys: Vec<super::V2PublicKey>,
	) -> V2ListPublicKeysResponse {
		self.public_keys = Some(public_keys);
		self
	}

	pub fn public_keys(&self) -> Option<&Vec<super::V2PublicKey>> {
		self.public_keys.as_ref()
	}

	pub fn reset_public_keys(&mut self) {
		self.public_keys = None;
	}
}
