// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2ListExecutionFunctionsResponse {
	/// All available functions to use in conditions.
	#[serde(rename = "functions")]
	#[serde(skip_serializing_if = "Option::is_none")]
	functions: Option<Vec<String>>,
}

impl V2ListExecutionFunctionsResponse {
	pub fn new() -> V2ListExecutionFunctionsResponse {
		V2ListExecutionFunctionsResponse { functions: None }
	}

	pub fn set_functions(&mut self, functions: Vec<String>) {
		self.functions = Some(functions);
	}

	pub fn with_functions(mut self, functions: Vec<String>) -> V2ListExecutionFunctionsResponse {
		self.functions = Some(functions);
		self
	}

	pub fn functions(&self) -> Option<&Vec<String>> {
		self.functions.as_ref()
	}

	pub fn reset_functions(&mut self) {
		self.functions = None;
	}
}
