// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2PublicKeySearchFilter {
	/// Filter the keys by one or multiple ids.
	#[serde(rename = "keyIdsFilter")]
	#[serde(skip_serializing_if = "Option::is_none")]
	key_ids_filter: Option<super::V2InIdsFilter>,
	/// Filter the keys by their active status.
	#[serde(rename = "activeFilter")]
	#[serde(skip_serializing_if = "Option::is_none")]
	active_filter: Option<bool>,
	/// Filter the keys by their expiration status.
	#[serde(rename = "expirationDateFilter")]
	#[serde(skip_serializing_if = "Option::is_none")]
	expiration_date_filter: Option<super::V2TimestampFilter>,
}

impl V2PublicKeySearchFilter {
	pub fn new() -> V2PublicKeySearchFilter {
		V2PublicKeySearchFilter {
			key_ids_filter: None,
			active_filter: None,
			expiration_date_filter: None,
		}
	}

	pub fn set_key_ids_filter(&mut self, key_ids_filter: super::V2InIdsFilter) {
		self.key_ids_filter = Some(key_ids_filter);
	}

	pub fn with_key_ids_filter(
		mut self,
		key_ids_filter: super::V2InIdsFilter,
	) -> V2PublicKeySearchFilter {
		self.key_ids_filter = Some(key_ids_filter);
		self
	}

	pub fn key_ids_filter(&self) -> Option<&super::V2InIdsFilter> {
		self.key_ids_filter.as_ref()
	}

	pub fn reset_key_ids_filter(&mut self) {
		self.key_ids_filter = None;
	}

	pub fn set_active_filter(&mut self, active_filter: bool) {
		self.active_filter = Some(active_filter);
	}

	pub fn with_active_filter(mut self, active_filter: bool) -> V2PublicKeySearchFilter {
		self.active_filter = Some(active_filter);
		self
	}

	pub fn active_filter(&self) -> Option<&bool> {
		self.active_filter.as_ref()
	}

	pub fn reset_active_filter(&mut self) {
		self.active_filter = None;
	}

	pub fn set_expiration_date_filter(&mut self, expiration_date_filter: super::V2TimestampFilter) {
		self.expiration_date_filter = Some(expiration_date_filter);
	}

	pub fn with_expiration_date_filter(
		mut self,
		expiration_date_filter: super::V2TimestampFilter,
	) -> V2PublicKeySearchFilter {
		self.expiration_date_filter = Some(expiration_date_filter);
		self
	}

	pub fn expiration_date_filter(&self) -> Option<&super::V2TimestampFilter> {
		self.expiration_date_filter.as_ref()
	}

	pub fn reset_expiration_date_filter(&mut self) {
		self.expiration_date_filter = None;
	}
}
