// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2ResponseExecution {
	/// Define a GRPC-method as condition. Before a response is returned to the
	/// client from this method, the execution is triggered.
	#[serde(rename = "method")]
	#[serde(skip_serializing_if = "Option::is_none")]
	method: Option<String>,
	/// Define a GRPC-service as condition. Before a response is returned to the
	/// client from any method of this service, the execution is triggered.
	#[serde(rename = "service")]
	#[serde(skip_serializing_if = "Option::is_none")]
	service: Option<String>,
	/// Define all calls as condition. Before a response is returned to the
	/// client from any available service, the execution is triggered.
	#[serde(rename = "all")]
	#[serde(skip_serializing_if = "Option::is_none")]
	all: Option<bool>,
}

impl V2ResponseExecution {
	pub fn new() -> V2ResponseExecution {
		V2ResponseExecution { method: None, service: None, all: None }
	}

	pub fn set_method(&mut self, method: String) {
		self.method = Some(method);
	}

	pub fn with_method(mut self, method: String) -> V2ResponseExecution {
		self.method = Some(method);
		self
	}

	pub fn method(&self) -> Option<&String> {
		self.method.as_ref()
	}

	pub fn reset_method(&mut self) {
		self.method = None;
	}

	pub fn set_service(&mut self, service: String) {
		self.service = Some(service);
	}

	pub fn with_service(mut self, service: String) -> V2ResponseExecution {
		self.service = Some(service);
		self
	}

	pub fn service(&self) -> Option<&String> {
		self.service.as_ref()
	}

	pub fn reset_service(&mut self) {
		self.service = None;
	}

	pub fn set_all(&mut self, all: bool) {
		self.all = Some(all);
	}

	pub fn with_all(mut self, all: bool) -> V2ResponseExecution {
		self.all = Some(all);
		self
	}

	pub fn all(&self) -> Option<&bool> {
		self.all.as_ref()
	}

	pub fn reset_all(&mut self) {
		self.all = None;
	}
}
