// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2SetExecutionResponse {
	/// The timestamp of the execution set.
	#[serde(rename = "setDate")]
	#[serde(skip_serializing_if = "Option::is_none")]
	set_date: Option<String>,
}

impl V2SetExecutionResponse {
	pub fn new() -> V2SetExecutionResponse {
		V2SetExecutionResponse { set_date: None }
	}

	pub fn set_set_date(&mut self, set_date: String) {
		self.set_date = Some(set_date);
	}

	pub fn with_set_date(mut self, set_date: String) -> V2SetExecutionResponse {
		self.set_date = Some(set_date);
		self
	}

	pub fn set_date(&self) -> Option<&String> {
		self.set_date.as_ref()
	}

	pub fn reset_set_date(&mut self) {
		self.set_date = None;
	}
}
