// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2TimestampFilter {
	/// Filter resources by timestamp.
	#[serde(rename = "timestamp")]
	#[serde(skip_serializing_if = "Option::is_none")]
	timestamp: Option<String>,
	/// Defines the condition (e.g., equals, before, after) that the timestamp
	/// of the retrieved resources should match.
	#[serde(rename = "method")]
	#[serde(skip_serializing_if = "Option::is_none")]
	method: Option<super::V2TimestampFilterMethod>,
}

impl V2TimestampFilter {
	pub fn new() -> V2TimestampFilter {
		V2TimestampFilter { timestamp: None, method: None }
	}

	pub fn set_timestamp(&mut self, timestamp: String) {
		self.timestamp = Some(timestamp);
	}

	pub fn with_timestamp(mut self, timestamp: String) -> V2TimestampFilter {
		self.timestamp = Some(timestamp);
		self
	}

	pub fn timestamp(&self) -> Option<&String> {
		self.timestamp.as_ref()
	}

	pub fn reset_timestamp(&mut self) {
		self.timestamp = None;
	}

	pub fn set_method(&mut self, method: super::V2TimestampFilterMethod) {
		self.method = Some(method);
	}

	pub fn with_method(mut self, method: super::V2TimestampFilterMethod) -> V2TimestampFilter {
		self.method = Some(method);
		self
	}

	pub fn method(&self) -> Option<&super::V2TimestampFilterMethod> {
		self.method.as_ref()
	}

	pub fn reset_method(&mut self) {
		self.method = None;
	}
}
