// SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a Zitadel instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum V2TargetFieldName {
	TARGET_FIELD_NAME_UNSPECIFIED,
	TARGET_FIELD_NAME_ID,
	TARGET_FIELD_NAME_CREATED_DATE,
	TARGET_FIELD_NAME_CHANGED_DATE,
	TARGET_FIELD_NAME_NAME,
	TARGET_FIELD_NAME_TARGET_TYPE,
	TARGET_FIELD_NAME_URL,
	TARGET_FIELD_NAME_TIMEOUT,
	TARGET_FIELD_NAME_INTERRUPT_ON_ERROR,
}
