/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a ZITADEL instance. This service is in beta state. It can AND
 * will continue breaking until a stable version is released.
 *
 * OpenAPI spec version: 2.0-beta
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2betaCreateTargetResponse {
	/// The unique identifier of the newly created target.
	#[serde(rename = "id")]
	id: Option<String>,
	/// The timestamp of the target creation.
	#[serde(rename = "creationDate")]
	creation_date: Option<String>,
	/// Key used to sign and check payload sent to the target.
	#[serde(rename = "signingKey")]
	signing_key: Option<String>,
}

impl V2betaCreateTargetResponse {
	pub fn new() -> V2betaCreateTargetResponse {
		V2betaCreateTargetResponse { id: None, creation_date: None, signing_key: None }
	}

	pub fn set_id(&mut self, id: String) {
		self.id = Some(id);
	}

	pub fn with_id(mut self, id: String) -> V2betaCreateTargetResponse {
		self.id = Some(id);
		self
	}

	pub fn id(&self) -> Option<&String> {
		self.id.as_ref()
	}

	pub fn reset_id(&mut self) {
		self.id = None;
	}

	pub fn set_creation_date(&mut self, creation_date: String) {
		self.creation_date = Some(creation_date);
	}

	pub fn with_creation_date(mut self, creation_date: String) -> V2betaCreateTargetResponse {
		self.creation_date = Some(creation_date);
		self
	}

	pub fn creation_date(&self) -> Option<&String> {
		self.creation_date.as_ref()
	}

	pub fn reset_creation_date(&mut self) {
		self.creation_date = None;
	}

	pub fn set_signing_key(&mut self, signing_key: String) {
		self.signing_key = Some(signing_key);
	}

	pub fn with_signing_key(mut self, signing_key: String) -> V2betaCreateTargetResponse {
		self.signing_key = Some(signing_key);
		self
	}

	pub fn signing_key(&self) -> Option<&String> {
		self.signing_key.as_ref()
	}

	pub fn reset_signing_key(&mut self) {
		self.signing_key = None;
	}
}
