/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a ZITADEL instance. This service is in beta state. It can AND
 * will continue breaking until a stable version is released.
 *
 * OpenAPI spec version: 2.0-beta
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2betaExecutionFieldName {}

impl V2betaExecutionFieldName {
	pub fn new() -> V2betaExecutionFieldName {
		V2betaExecutionFieldName {}
	}
}

// TODO enum
// List of v2betaExecutionFieldName
//const (
//
//
//
//)
