/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a ZITADEL instance. This service is in beta state. It can AND
 * will continue breaking until a stable version is released.
 *
 * OpenAPI spec version: 2.0-beta
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2betaExecutionTypeFilter {
	/// Defines the type to query for.
	#[serde(rename = "executionType")]
	execution_type: Option<super::V2betaExecutionType>,
}

impl V2betaExecutionTypeFilter {
	pub fn new() -> V2betaExecutionTypeFilter {
		V2betaExecutionTypeFilter { execution_type: None }
	}

	pub fn set_execution_type(&mut self, execution_type: super::V2betaExecutionType) {
		self.execution_type = Some(execution_type);
	}

	pub fn with_execution_type(
		mut self,
		execution_type: super::V2betaExecutionType,
	) -> V2betaExecutionTypeFilter {
		self.execution_type = Some(execution_type);
		self
	}

	pub fn execution_type(&self) -> Option<&super::V2betaExecutionType> {
		self.execution_type.as_ref()
	}

	pub fn reset_execution_type(&mut self) {
		self.execution_type = None;
	}
}
