/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a ZITADEL instance. This service is in beta state. It can AND
 * will continue breaking until a stable version is released.
 *
 * OpenAPI spec version: 2.0-beta
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum V2betaTextFilterMethod {
	TEXT_FILTER_METHOD_EQUALS,
	TEXT_FILTER_METHOD_EQUALS_IGNORE_CASE,
	TEXT_FILTER_METHOD_STARTS_WITH,
	TEXT_FILTER_METHOD_STARTS_WITH_IGNORE_CASE,
	TEXT_FILTER_METHOD_CONTAINS,
	TEXT_FILTER_METHOD_CONTAINS_IGNORE_CASE,
	TEXT_FILTER_METHOD_ENDS_WITH,
	TEXT_FILTER_METHOD_ENDS_WITH_IGNORE_CASE,
}
