/*
 * Action Service
 *
 * This API is intended to manage custom executions (previously known as
 * actions) in a ZITADEL instance. This service is in beta state. It can AND
 * will continue breaking until a stable version is released.
 *
 * OpenAPI spec version: 2.0-beta
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct V2betaTargetFilter {
	/// the id of the targets to include
	#[serde(rename = "targetId")]
	target_id: Option<String>,
}

impl V2betaTargetFilter {
	pub fn new() -> V2betaTargetFilter {
		V2betaTargetFilter { target_id: None }
	}

	pub fn set_target_id(&mut self, target_id: String) {
		self.target_id = Some(target_id);
	}

	pub fn with_target_id(mut self, target_id: String) -> V2betaTargetFilter {
		self.target_id = Some(target_id);
		self
	}

	pub fn target_id(&self) -> Option<&String> {
		self.target_id.as_ref()
	}

	pub fn reset_target_id(&mut self) {
		self.target_id = None;
	}
}
