/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::users::models;

#[derive(Debug, Serialize, Deserialize)]
pub struct IdpldapAccessInformation {
	#[serde(rename = "attributes")]
	attributes: Option<Value>,
}

impl IdpldapAccessInformation {
	pub fn new() -> IdpldapAccessInformation {
		IdpldapAccessInformation { attributes: None }
	}

	pub fn set_attributes(&mut self, attributes: Value) {
		self.attributes = Some(attributes);
	}

	pub fn with_attributes(mut self, attributes: Value) -> IdpldapAccessInformation {
		self.attributes = Some(attributes);
		self
	}

	pub fn attributes(&self) -> Option<&Value> {
		self.attributes.as_ref()
	}

	pub fn reset_attributes(&mut self) {
		self.attributes = None;
	}
}
