/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::users::models;

#[derive(Debug, Serialize, Deserialize)]
pub struct IdpsamlAccessInformation {
	#[serde(rename = "assertion")]
	assertion: Option<String>,
}

impl IdpsamlAccessInformation {
	pub fn new() -> IdpsamlAccessInformation {
		IdpsamlAccessInformation { assertion: None }
	}

	pub fn set_assertion(&mut self, assertion: String) {
		self.assertion = Some(assertion);
	}

	pub fn with_assertion(mut self, assertion: String) -> IdpsamlAccessInformation {
		self.assertion = Some(assertion);
		self
	}

	pub fn assertion(&self) -> Option<&String> {
		self.assertion.as_ref()
	}

	pub fn reset_assertion(&mut self) {
		self.assertion = None;
	}
}
