/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

use crate::users::models;

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct LastNameQuery {
	#[serde(rename = "lastName")]
	last_name: String,
	/// defines which text equality method is used
	#[serde(rename = "method")]
	method: Option<models::TextQueryMethod>,
}

impl LastNameQuery {
	/// Query for users with a specific last name.
	pub fn new(last_name: String) -> LastNameQuery {
		LastNameQuery { last_name, method: None }
	}

	pub fn set_last_name(&mut self, last_name: String) {
		self.last_name = last_name;
	}

	pub fn with_last_name(mut self, last_name: String) -> LastNameQuery {
		self.last_name = last_name;
		self
	}

	pub fn last_name(&self) -> &String {
		&self.last_name
	}

	pub fn set_method(&mut self, method: models::TextQueryMethod) {
		self.method = Some(method);
	}

	pub fn with_method(mut self, method: models::TextQueryMethod) -> LastNameQuery {
		self.method = Some(method);
		self
	}

	pub fn method(&self) -> Option<&models::TextQueryMethod> {
		self.method.as_ref()
	}

	pub fn reset_method(&mut self) {
		self.method = None;
	}
}
