/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

use crate::users::models;

#[derive(Debug, Serialize, Deserialize)]
pub struct ProtobufAny {
	#[serde(rename = "@type")]
	at_type: Option<String>,
}

impl ProtobufAny {
	pub fn new() -> ProtobufAny {
		ProtobufAny { at_type: None }
	}

	pub fn set_type(&mut self, at_type: String) {
		self.at_type = Some(at_type);
	}

	pub fn with_type(mut self, at_type: String) -> ProtobufAny {
		self.at_type = Some(at_type);
		self
	}

	pub fn at_type(&self) -> Option<&String> {
		self.at_type.as_ref()
	}

	pub fn reset_type(&mut self) {
		self.at_type = None;
	}
}
