/*
 * User Service
 *
 * This API is intended to manage users in a ZITADEL instance.
 *
 * OpenAPI spec version: 2.0
 * Contact: hi@zitadel.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct UserServiceVerifyTotpRegistrationBody {
	/// Code generated by TOTP app or device
	#[serde(rename = "code")]
	code: String,
}

impl UserServiceVerifyTotpRegistrationBody {
	pub fn new(code: String) -> UserServiceVerifyTotpRegistrationBody {
		UserServiceVerifyTotpRegistrationBody { code }
	}

	pub fn set_code(&mut self, code: String) {
		self.code = code;
	}

	pub fn with_code(mut self, code: String) -> UserServiceVerifyTotpRegistrationBody {
		self.code = code;
		self
	}

	pub fn code(&self) -> &String {
		&self.code
	}
}
